### ISSUE TITLE
Ribbon Bra hint

### ISSUE THREAD

**Issue by Alua7** [MoArtis/RCGMod#33]
It seems like Ribbon Bra still not matching its description. Can its hint be changed to actual "100% (not 10%) chance to get 2 items from vending machines and crates". Hope this item they will not fix :1st_place_medal:

**Comment by MoArtis** [comment]
Let me check the code. That sounds easy to check.

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/73239273-98c3d880-41d6-11ea-8e85-41970bdb29bd.png)
Apparently they are testing for the wrong effect. And they just test if it is equipped or not. 🤔

**Comment by MoArtis** [comment]
Apparently it is a misconfiguration issue after they changed the EquipEffect enum. The item is also using that reflect1Damage thing.
And again it never test for a chance to apply the effect so it is always in effect.
I will just override the translation using the mod's data to say 100% instead of 10%.
![image](https://user-images.githubusercontent.com/3904610/73244145-31ad2080-41e4-11ea-853e-c15b745a0a39.png)

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/73245440-2c9da080-41e7-11ea-92a6-49396286c2ea.png)
![image](https://user-images.githubusercontent.com/3904610/73245456-3921f900-41e7-11ea-94bd-5c32c41b4f8f.png)

**Comment by Alua7** [comment]
And special thanks for adding json support so I could fix some localization's errors for my language <3
